title: oxdjww
url: "https://oxdjww.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #



sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "/CV.pdf"
 - name: "Contact"
   link: "/contact"

footer_redirect: "20000322"
